name: Deploy to GCP

on:
  push:
    branches:
      - testing
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: replace
      
      - name: Deploy to GCP server
        run: |
          ssh ubuntu@34.32.86.172 "cd ~/gdsd-summer-2025-team5 && \
          git checkout testing && \
          git remote set-url origin https://${{ secrets.USERNAME_GITHUB }}:${{ secrets.PAT_GITHUB }}@github.com/$(echo ${{ github.repository }}).git && \
          sudo git pull && \
          docker compose -f docker-compose-apps.yml down -v && \
          docker compose -f docker-compose-apps.yml up -d --build" 